theme: jekyll-theme-minimal

title: El Bueno, el Ralo, y el Feo
description: >
  Blog for our ICPC team.
logo: "/assets/img/logo.png"

baseurl: ""
permalink: /:year/:title:output_ext

# CSS
sass:
  sass_dir: "/assets/css"
style: :compressed
